version: 0.0
os: windows
files:
  - source: .\myTextFile
    destination: E:\AltaSoft Freelancer Project
  - source: \
    destination: E:\AltaSoft Freelancer Project
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
    - location: scripts/start_server
      timeout: 300
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300